# webサーバーの設定
webserver:

  # wordpressのイメージを取得 （ローカルにないので、DockerHubから最新版を取得）
  image: wordpress

  # 80番ポートに転送 ホストポート：コンテナポート
  ports:
   - "80:80"

  # 別コンテナのエイリアスを設定 （リンク）
  links:
   - "dbserver:mysql"


# dbサーバーの設定
dbserver:

  # mysqlのイメージを取得 （ローカルにないので、DockerHubから最新版を取得）
  image: mysql

  # データのマウント先を指定 （さっき作ったdataonlyコンテナ）
  volumes_from:
   - dataonly

  # 環境変数
  environment:
   MYSQL_ROOT_PASSWORD: password